# Generated by Django 5.0.7 on 2024-10-30 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0009_chiptype_fasta_index'),
        ('canvas', '0010_report_chipsample'),
    ]

    operations = [
    ]
