# Generated by Django 5.0.7 on 2024-11-13 11:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0011_merge_20241030_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedgraph',
            name='bedgraph_type',
            field=models.CharField(choices=[('LRR', 'Log R Ratio'), ('BAF', 'B Allele Frequency'), ('CNV_pos', 'CNV positive'), ('CNV_neg', 'CNV negative'), ('LRR_smooth', 'LRR smooth')], max_length=50),
        ),
        migrations.AlterField(
            model_name='chiptype',
            name='fasta',
            field=models.FileField(blank=True, upload_to='analysis_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['fa'])]),
        ),
        migrations.AlterField(
            model_name='chiptype',
            name='fasta_index',
            field=models.FileField(blank=True, upload_to='analysis_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['fai'])]),
        ),
    ]
