# Generated by Django 5.0.7 on 2024-11-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canvas", "0012_alter_bedgraph_bedgraph_type_alter_chiptype_fasta_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="classifications",
            field=models.ManyToManyField(blank=True, to="canvas.classification"),
        ),
    ]
