# Generated by Django 5.0.7 on 2024-12-22 19:37

import canvas.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canvas", "0015_remove_old_path_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "fasta",
                    models.FileField(
                        blank=True,
                        upload_to="analysis_files/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["fa"]
                            )
                        ],
                    ),
                ),
                (
                    "fasta_index",
                    models.FileField(
                        blank=True,
                        upload_to="analysis_files/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["fai"]
                            )
                        ],
                    ),
                ),
                (
                    "band",
                    models.FileField(
                        blank=True,
                        upload_to=canvas.models.analysis_files_directory_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["txt"]
                            )
                        ],
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="chiptype",
            name="band",
        ),
        migrations.RemoveField(
            model_name="chiptype",
            name="fasta",
        ),
        migrations.RemoveField(
            model_name="chiptype",
            name="fasta_index",
        ),
        migrations.AddField(
            model_name="chiptype",
            name="genome",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="canvas.genome",
            ),
        ),
    ]
