# Generated by Django 5.0.7 on 2024-12-22 19:50

import canvas.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canvas", "0016_genome_remove_chiptype_band_remove_chiptype_fasta_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genome",
            name="band",
            field=models.FileField(
                blank=True,
                upload_to=canvas.models.genome_directory_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["txt", "band"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="genome",
            name="fasta",
            field=models.FileField(
                blank=True,
                upload_to=canvas.models.genome_directory_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["fa", "fasta"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="genome",
            name="fasta_index",
            field=models.FileField(
                blank=True,
                upload_to=canvas.models.genome_directory_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["fai", "fasta.fai"]
                    )
                ],
            ),
        ),
    ]
