# Generated by Django 5.0.7 on 2025-01-07 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canvas", "0017_alter_genome_band_alter_genome_fasta_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idat",
            name="chipsample",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="idat",
                to="canvas.chipsample",
            ),
        ),
    ]
