# Generated by Django 5.0.7 on 2025-01-16 10:51

import canvas.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canvas", "0019_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="chiptype",
            name="hmm",
            field=models.FileField(
                blank=True,
                upload_to=canvas.models.analysis_files_directory_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["hmm"]
                    )
                ],
            ),
        ),
    ]
