#!/usr/bin/env python3

acmg_loss = {
    "type": "loss",
    "sections": [
        {
            "id": "section1",
            "name": "Section 1: Initial Assessment of Genomic Content",
            "evidences": {
                "group1": [
                    {
                        "id": "e1A",
                        "name": "1A",
                        "description": "Contains protein-coding or other known functionally important elements",
                        "score": 0,
                        "suggested": 0,
                        "min": 0,
                        "max": 1,
                    },
                    {
                        "id": "e1B",
                        "name": "1B",
                        "description": "Does NOT contain protein-coding or any known functionally important elements",
                        "score": 0,
                        "suggested": -0.60,
                        "min": -0.60,
                        "max": -0.60,
                    },
                ],
            },
        },
        {
            "id": "section2",
            "name": "Section 2: Overlap with Established/Predicted HI or Established Benign Genes/Genomic Regions",
            "evidences": {
                "group1": [
                    {
                        "id": "e2A",
                        "name": "2A",
                        "description": "Complete overlap of an established HI gene/genomic region",
                        "score": 0,
                        "suggested": 1.00,
                        "min": 0.00,
                        "max": 1.00,
                        "slider": True,
                    },
                    {
                        "id": "e2B",
                        "name": "2B",
                        "description": "Partial overlap of an established HI genomic region",
                        "score": 0,
                        "suggested": 0,
                        "min": 0,
                        "max": 0,
                    },
                ],
                "group2": [
                    {
                        "id": "e2C1",
                        "name": "2C-1",
                        "description": "Partial overlap with the 5’ end of an established HI gene, and coding sequence is involved",
                        "score": 0,
                        "suggested": 0.90,
                        "min": 0.45,
                        "max": 1.00,
                        "slider": True,
                    },
                    {
                        "id": "e2C2",
                        "name": "2C-2",
                        "description": "Partial overlap with the 5’ end of an established HI gene, and only the 5’ UTR is involved",
                        "score": 0,
                        "suggested": 0,
                        "min": 0,
                        "max": 0.45,
                        "slider": True,
                    },
                ],
                "group3": [
                    {
                        "id": "e2D1",
                        "name": "2D-1",
                        "description": "Partial overlap with the 3’ untranslated region of an established HI gene",
                        "score": 0,
                        "suggested": 0,
                        "min": 0,
                        "max": 0,
                    },
                    {
                        "id": "e2D2",
                        "name": "2D-2",
                        "description": "Partial overlap with the last exon of an established HI gene. Other pathogenic variants have been reported in this exon.",
                        "score": 0,
                        "suggested": 0.90,
                        "min": 0.45,
                        "max": 0.90,
                        "slider": True,
                    },
                    {
                        "id": "e2D3",
                        "name": "2D-3",
                        "description": "Partial overlap with the last exon of an established HI gene. No other pathogenic variants have been reported in this exon.",
                        "score": 0,
                        "suggested": 0.30,
                        "min": 0,
                        "max": 0.45,
                        "slider": True,
                    },
                    {
                        "id": "e2D4",
                        "name": "2D-4",
                        "description": "Includes other exons in addition to the last exon. Nonsense-mediated decay is expected.",
                        "score": 0,
                        "suggested": 0.90,
                        "min": 0.45,
                        "max": 1.00,
                        "slider": True,
                    },
                ],
                "group4": [
                    {
                        "id": "e2E",
                        "name": "2E",
                        "description": "Both breakpoints are within the same gene (intragenic CNV; gene-level sequence variant)",
                        "score": 0,
                        "suggested": "null",
                        "ranges": {
                            "PVS1": [0.45, 0.90],
                            "PVS1_Strong": [0.30, 0.90],
                            "PVS1_Moderate": [0.15, 0.45],
                            "PVS1_Supporting": [0, 0.30],
                        },
                    },
                    {
                        "id": "e2F",
                        "name": "2F",
                        "description": "Completely contained within an established benign CNV region",
                        "score": 0,
                        "suggested": -1.00,
                        "min": -1.00,
                        "max": -1.00,
                    },
                    {
                        "id": "e2G",
                        "name": "2G",
                        "description": "Overlaps an established benign CNV, but includes additional genomic material",
                        "score": 0,
                        "suggested": 0,
                        "min": 0,
                        "max": 0,
                    },
                    {
                        "id": "e2H",
                        "name": "2H",
                        "description": "Two or more HI predictors suggest at least one gene in the interval is haploinsufficient",
                        "score": 0,
                        "suggested": 0.15,
                        "min": 0.15,
                        "max": 0.15,
                    },
                ],
            },
        },
        {
            "id": "section3",
            "name": "Section 3: Evaluation of Gene Number",
            "evidences": {
                "group1": [
                    {
                        "id": "e3A",
                        "name": "3A",
                        "description": "0-24 genes",
                        "score": 0,
                        "suggested": 0,
                        "min": 0,
                        "max": 0,
                    },
                    {
                        "id": "e3B",
                        "name": "3B",
                        "description": "25-34 genes",
                        "score": 0,
                        "suggested": 0.45,
                        "min": 0.45,
                        "max": 0.45,
                    },
                    {
                        "id": "e3C",
                        "name": "3C",
                        "description": "35+ genes",
                        "score": 0,
                        "suggested": 0.90,
                        "min": 0.90,
                        "max": 0.90,
                    },
                ]
            },
        },
        {
            "id": "section4",
            "name": "Section 4: Detailed Evaluation of Genomic Content Using Cases from Published Literature, Public Databases, and/or Internal Lab Data",
            "evidences": {
                "group1": [
                    {
                        "id": "e4A",
                        "name": "4A",
                        "description": "Reported proband has a highly specific and relatively unique phenotype; confirmed de novo",
                        "score": 0,
                        "suggested": 0.45,
                        "min": 0.15,
                        "max": 0.45,
                    },
                    {
                        "id": "e4B",
                        "name": "4B",
                        "description": "Reported proband has a highly specific phenotype; consistent with the gene/genomic region, not necessarily unique; confirmed de novo",
                        "score": 0,
                        "suggested": 0.30,
                        "min": 0,
                        "max": 0.45,
                    },
                    {
                        "id": "e4C",
                        "name": "4C",
                        "description": "Reported proband has a consistent phenotype but not highly specific; confirmed de novo",
                        "score": 0,
                        "suggested": 0.15,
                        "min": 0,
                        "max": 0.30,
                    },
                    {
                        "id": "e4D",
                        "name": "4D",
                        "description": "Reported proband has an inconsistent phenotype with the gene/genomic region",
                        "score": 0,
                        "suggested": -0.30,
                        "min": -0.30,
                        "max": 0,
                    },
                ],
                "group2": [
                    {
                        "id": "e4E",
                        "name": "4E",
                        "description": "Reported proband has a highly specific phenotype; inheritance is unknown",
                        "score": 0,
                        "suggested": 0.10,
                        "min": 0,
                        "max": 0.15,
                    },
                    {
                        "id": "e4F",
                        "name": "4F",
                        "description": "Segregation: 3-4 observed cases",
                        "score": 0,
                        "suggested": 0.15,
                        "min": 0,
                        "max": 0.45,
                    },
                    {
                        "id": "e4G",
                        "name": "4G",
                        "description": "Segregation: 5-6 observed cases",
                        "score": 0,
                        "suggested": 0.30,
                        "min": 0,
                        "max": 0.45,
                    },
                    {
                        "id": "e4H",
                        "name": "4H",
                        "description": "Segregation: 7+ observed cases",
                        "score": 0,
                        "suggested": 0.45,
                        "min": 0,
                        "max": 0.45,
                    },
                ],
                "group3": [
                    {
                        "id": "e4I",
                        "name": "4I",
                        "description": "Non-segregation: Variant not found in other affected family members",
                        "score": 0,
                        "suggested": -0.45,
                        "min": -0.45,
                        "max": 0,
                    },
                    {
                        "id": "e4J",
                        "name": "4J",
                        "description": "Variant found in unaffected family members with the proband's phenotype",
                        "score": 0,
                        "suggested": -0.30,
                        "min": -0.30,
                        "max": 0,
                    },
                    {
                        "id": "e4K",
                        "name": "4K",
                        "description": "Variant found in unaffected family members with a non-specific phenotype",
                        "score": 0,
                        "suggested": -0.15,
                        "min": -0.15,
                        "max": 0,
                    },
                    {
                        "id": "e4L",
                        "name": "4L",
                        "description": "Case-control evidence: Statistically significant increase in cases with a specific phenotype",
                        "score": 0,
                        "suggested": 0.45,
                        "min": 0,
                        "max": 0.45,
                    },
                ],
                "group4": [
                    {
                        "id": "e4M",
                        "name": "4M",
                        "description": "Case-control evidence: Statistically significant increase in cases with a non-specific phenotype",
                        "score": 0,
                        "suggested": 0.30,
                        "min": 0,
                        "max": 0.30,
                    },
                    {
                        "id": "e4N",
                        "name": "4N",
                        "description": "Case-control evidence: No significant difference between cases and controls",
                        "score": 0,
                        "suggested": -0.90,
                        "min": -0.90,
                        "max": 0,
                    },
                    {
                        "id": "e4O",
                        "name": "4O",
                        "description": "Overlap with common population variation",
                        "score": 0,
                        "suggested": -1.00,
                        "min": -1.00,
                        "max": 0,
                    },
                ],
            },
        },
        {
            "id": "section5",
            "name": "Section 5: Evaluation of Inheritance Pattern/Family History for Patient Being Studied",
            "evidences": {
                "group1": [
                    {
                        "id": "e5A",
                        "name": "5A",
                        "description": "Observed CNV is de novo",
                        "score": 0,
                        "suggested": 0.45,
                        "min": 0.15,
                        "max": 0.45,
                    },
                    {
                        "id": "e5B",
                        "name": "5B",
                        "description": "Observed CNV is inherited; specific phenotype, no family history",
                        "score": 0,
                        "suggested": -0.30,
                        "min": -0.45,
                        "max": 0,
                    },
                    {
                        "id": "e5C",
                        "name": "5C",
                        "description": "Observed CNV is inherited; non-specific phenotype, no family history",
                        "score": 0,
                        "suggested": -0.15,
                        "min": -0.30,
                        "max": 0,
                    },
                    {
                        "id": "e5D",
                        "name": "5D",
                        "description": "Observed CNV segregates with a consistent phenotype in family",
                        "score": 0,
                        "suggested": 0.45,
                        "min": 0.15,
                        "max": 0.45,
                    },
                ],
                "group2": [
                    {
                        "id": "e5E",
                        "name": "5E",
                        "description": "Non-segregation: Use appropriate scoring from Section 4",
                        "score": 0,
                        "suggested": -0.45,
                        "min": -0.45,
                        "max": 0,
                    },
                    {
                        "id": "e5F",
                        "name": "5F",
                        "description": "Inheritance information is unavailable or uninformative",
                        "score": 0,
                        "suggested": 0,
                        "min": 0,
                        "max": 0,
                    },
                    {
                        "id": "e5G",
                        "name": "5G",
                        "description": "Inheritance information unavailable; non-specific phenotype consistent with similar cases",
                        "score": 0,
                        "suggested": 0.10,
                        "min": 0,
                        "max": 0.15,
                    },
                    {
                        "id": "e5H",
                        "name": "5H",
                        "description": "Inheritance information unavailable; highly specific phenotype consistent with similar cases",
                        "score": 0,
                        "suggested": 0.30,
                        "min": 0,
                        "max": 0.30,
                    },
                ],
            },
        },
    ],
}

acmg_gain = {
    "type": "gain",
    "sections": [
        {
            "id": "section1",
            "name": "Section 1: Initial Assessment of Genomic Content",
            "evidences": {
                "group1": [
                    {
                        "id": "e1A",
                        "name": "1A",
                        "description": "Contains protein-coding or other known functionally important elements",
                        "score": 0,
                        "suggested": 0,
                        "min": 0,
                        "max": 1,
                    },
                    {
                        "id": "e1B",
                        "name": "1B",
                        "description": "Does NOT contain protein-coding or any known functionally important elements",
                        "score": 0,
                        "suggested": -0.60,
                        "min": -0.60,
                        "max": -0.60,
                    },
                ]
            },
        },
        {
            "id": "section2",
            "name": "Section 2: Overlap with Established Triplosensitive (TS), Haploinsufficient (HI), or Benign Genes or Genomic Regions",
            "evidences": {
                "group1": [
                    {
                        "id": "e2A",
                        "name": "2A",
                        "description": "Complete overlap of an established TS gene/genomic region",
                        "score": 0,
                        "suggested": 1.00,
                        "min": 0.00,
                        "max": 1.00,
                    },
                    {
                        "id": "e2B",
                        "name": "2B",
                        "description": "Partial overlap of an established TS region. Observed CNV does NOT contain the known causative gene/critical region OR unclear if affected OR no specific causative gene.",
                        "score": 0,
                        "suggested": 0,
                        "min": 0,
                        "max": 0,
                    },
                    {
                        "id": "e2C",
                        "name": "2C",
                        "description": "Identical in gene content to the established benign copy number gain",
                        "score": 0,
                        "suggested": -1.00,
                        "min": -1.00,
                        "max": -1.00,
                    },
                ]
            },
        },
        {
            "id": "section3",
            "name": "Section 3: Evaluation of Gene Number",
            "evidences": {
                "group1": [
                    {
                        "id": "e3A",
                        "name": "3A",
                        "description": "0-34 protein-coding RefSeq genes wholly or partially included in the gain",
                        "score": 0,
                        "suggested": 0,
                        "min": 0,
                        "max": 0,
                    },
                    {
                        "id": "e3B",
                        "name": "3B",
                        "description": "35-49 protein-coding RefSeq genes wholly or partially included in the gain",
                        "score": 0,
                        "suggested": 0.45,
                        "min": 0.45,
                        "max": 0.45,
                    },
                    {
                        "id": "e3C",
                        "name": "3C",
                        "description": "50 or more protein-coding RefSeq genes wholly or partially included in the gain",
                        "score": 0,
                        "suggested": 0.90,
                        "min": 0.90,
                        "max": 0.90,
                    },
                ]
            },
        },
        {
            "id": "section4",
            "name": "Section 4: Detailed Evaluation of Genomic Content Using Cases from Published Literature, Public Databases, and/or Internal Lab Data",
            "evidences": {
                "group1": [
                    {
                        "id": "e4A",
                        "name": "4A",
                        "description": "Reported phenotype is highly specific and relatively unique to the gene or genomic region; confirmed de novo",
                        "score": 0,
                        "suggested": 0.45,
                        "min": 0.15,
                        "max": 0.45,
                    },
                    {
                        "id": "e4B",
                        "name": "4B",
                        "description": "Reported phenotype is consistent with the gene/genomic region but not necessarily unique; confirmed de novo",
                        "score": 0,
                        "suggested": 0.30,
                        "min": 0,
                        "max": 0.45,
                    },
                    {
                        "id": "e4C",
                        "name": "4C",
                        "description": "Reported phenotype is consistent with the gene/genomic region but not highly specific; confirmed de novo",
                        "score": 0,
                        "suggested": 0.15,
                        "min": 0,
                        "max": 0.30,
                    },
                    {
                        "id": "e4D",
                        "name": "4D",
                        "description": "Reported phenotype is NOT consistent with the gene/genomic region or not consistent in general",
                        "score": 0,
                        "suggested": -0.30,
                        "min": -0.30,
                        "max": -0.30,
                    },
                ]
            },
        },
        {
            "id": "section5",
            "name": "Section 5: Evaluation of Inheritance Patterns/Family History for Patient Being Studied",
            "evidences": {
                "group1": [
                    {
                        "id": "e5A",
                        "name": "5A",
                        "description": "Observed copy number gain is DE NOVO",
                        "score": 0,
                        "suggested": 0.45,
                        "min": 0.15,
                        "max": 0.45,
                    },
                    {
                        "id": "e5B",
                        "name": "5B",
                        "description": "Copy number gain is inherited from an unaffected parent; patient has specific phenotype",
                        "score": 0,
                        "suggested": -0.30,
                        "min": -0.30,
                        "max": -0.45,
                    },
                    {
                        "id": "e5C",
                        "name": "5C",
                        "description": "Copy number gain is inherited from an unaffected parent; patient has non-specific phenotype",
                        "score": 0,
                        "suggested": -0.15,
                        "min": -0.15,
                        "max": -0.30,
                    },
                    {
                        "id": "e5D",
                        "name": "5D",
                        "description": "CNV segregates with consistent phenotype observed in the patient’s family",
                        "score": 0,
                        "suggested": 0.45,
                        "min": 0.15,
                        "max": 0.45,
                    },
                ]
            },
        },
    ],
}
